docs: "docs/*"
docker: "docker/*"
notebooks: "notebooks/*"
env: "minihack/envs/*"
agent: "minihack/agent/*"
torchbeast: "minihack/agent/polybeast/*"
rllib: "minihack/agent/rllib/*"
script: "minihack/scripts/*"
src: "minihack/*.py"
